{% set name = "hpp-gepetto-viewer" %}
{% set version = "4.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/hpp-gepetto-viewer/releases/download/v{{ version }}/hpp-gepetto-viewer-{{ version }}.tar.gz
  sha256: ae6c696a560d7bff8503006a3d5556ba05df0449944e177f80e08aaa17156b67

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
    - {{ cdt('libxdamage-devel') }}       # [linux]
    - {{ cdt('libx11-devel') }}           # [linux]
    - {{ cdt('libxfixes') }}              # [linux]
    - {{ cdt('libxxf86vm') }}             # [linux]
    - {{ cdt('libxext') }}                # [linux]
  host:
    - hpp-util  {{ version }}
    - hpp-statistics  {{ version }}
    - hpp-pinocchio  {{ version }}
    - hpp-constraints  {{ version }}
    - hpp-core  {{ version }}
    - hpp-template-corba  {{ version }}
    - hpp-corbaserver  {{ version }}
    - hpp-manipulation  {{ version }}
    - hpp-manipulation-urdf  {{ version }}
    - hpp-manipulation-corba  {{ version }}
    - gepetto-viewer-corba
    - gepetto-viewer
    - boost-cpp
    - assimp
    - octomap
    - urdfdom
    - ffmpeg
    - qt-main
    - openscenegraph
    - openscenegraph-osgqt
    - python
  run:
    - numpy
    - python
    - boost-cpp

test:
  requires:
    - pkg-config
    - hpp-corbaserver  {{ version }}
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
