{% set name = "hpp-gepetto-viewer" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/hpp-gepetto-viewer/releases/download/v{{ version }}/hpp-gepetto-viewer-{{ version }}.tar.gz
  sha256: d8378e2bdd3fc8974d7614dc2da8f5090818111a054b39ff5f757756bc53ff61

build:
  number: 1
  skip: true  # [win or python_impl == 'pypy']
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
  host:
    - hpp-util  {{ version }}
    - hpp-statistics  {{ version }}
    - hpp-pinocchio  {{ version }}
    - hpp-constraints  {{ version }}
    - hpp-core  {{ version }}
    - hpp-template-corba  {{ version }}
    - hpp-corbaserver  {{ version }}
    - hpp-manipulation  {{ version }}
    - hpp-manipulation-urdf  {{ version }}
    - hpp-manipulation-corba  {{ version }}
    - gepetto-viewer-corba
    - gepetto-viewer
    - libboost-devel
    - assimp
    - octomap
    - urdfdom
    - qt-main
    - openscenegraph
    - openscenegraph-osgqt
    - python
    - qhull
    - qhull-static
  run:
    - numpy
    - python
    - qhull
    - qhull-static

test:
  requires:
    - pkg-config
    - hpp-corbaserver  {{ version }}
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: https://github.com/humanoid-path-planner/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ name }}

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
